metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      codebgp.com/platform-monitor: "true"
resources:
  requests:
    cpu: 15m
    memory: 64M
  limits:
    memory: 64M
