apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-app 
commonLabels:
  app: demo-app

resources:
- ./namespace.yaml
- ./deployment.yaml
- ./service.yaml
- ./rbac.yaml
- ./prometheus.yaml
- ./service-monitor.yaml
- ./service-monitor-monitoring.yaml
