---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app-monitor
spec:
  endpoints:
  - interval: 30s
    port: http-port
  selector:
    matchLabels:
      app: demo-app-service

