apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-test
spec:
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  podMonitorSelector: {}
  resources:
    requests:
      memory: 400Mi
