commonLabels: 
  codebgp.com/platform-monitor: "true"
alertmanager:
  config:
    global:
        resolve_timeout: 5m
    inhibit_rules:
        - equal:
            - namespace
            - alertname
          source_matchers:
            - severity = critical
          target_matchers:
            - severity =~ warning|info
        - equal:
            - namespace
            - alertname
          source_matchers:
            - severity = warning
          target_matchers:
            - severity = info
        - equal:
            - namespace
          source_matchers:
            - alertname = InfoInhibitor
          target_matchers:
            - severity = info
    route:
        group_by:
            - namespace
        group_interval: 5m
        group_wait: 30s
        receiver: slack
        repeat_interval: 12h
        routes:
            - receiver: "null"
              matchers:
                - alertname =~ "InfoInhibitor|Watchdog"
            - receiver: slack
              matchers:
                - severity =~ "warning|critical"
    receivers:
        - name: "null"
        - name: slack
          slack_configs:
            - api_url: ${SLACK_WEBHOOK_URL}
              channel: ${SLACK_CHANNEL}
              icon_url: https://avatars3.githubusercontent.com/u/3380462
              send_resolved: true
              text: |
                {{ range .Alerts -}}
                *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
                *Tenant:* {{ .Labels.namespace }}
                *Description:* {{ .Annotations.description }}
                *Details:*
                  {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                  {{ end }}
                {{ end }}
              title: |
                [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
                {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
                  {{" "}}(
                  {{- with .CommonLabels.Remove .GroupLabels.Names }}
                    {{- range $index, $label := .SortedPairs -}}
                      {{ if $index }}, {{ end }}
                      {{- $label.Name }}="{{ $label.Value -}}"
                    {{- end }}
                  {{- end -}}
                  )
                {{- end }}
    templates:
        - /etc/alertmanager/config/*.tmpl
alertmanagerSpec:
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: default-rwo
coreDns:
  enabled: true
#defaultRules:
#  disabled:
#    KubeControllerManagerDown: true
#    KubeProxyDown: true
#    KubeSchedulerDown: true
#  rules:
#    etcd: false
#    kubeProxy: false
grafana:
  defaultDashboardsTimezone: utc+3
  serviceMonitor:
    labels:
      codebgp.com/platform-monitor: "true"  
kubeDns:
  enabled: true
prometheus:
  enabled: true
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    podMonitorSelector:
       matchLabels:
         codebgp.com/platform-monitor: "true"
    serviceMonitorSelector:
       matchLabels:
         codebgp.com/platform-monitor: "true"
    retention: 48h
    enableAdminAPI: true
    enableRemoteWriteReceiver: true
    resources:
      requests:
        memory: 2Gi
      limits:
        memory: 16Gi
    storageSpec:
#      volumeClaimTemplate:
#        spec:
#          accessModes:
#            - ReadWriteOnce
#          resources:
#            requests:
#              storage: 100Gi
#          storageClassName: premium-rwo
      emptyDir:
        medium: Memory
#prometheusOperator:
#  admissionWebhooks:
#    certManager:
#      enabled: true
nodeExporter:
  enabled: true
prometheus-node-exporter:
  podLabels:
    codebgp.com/platform-monitor: "true"
kube-state-metrics:
  customLabels:
    codebgp.com/platform-monitor: "true"
